# Generated by Django 3.2 on 2024-10-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('cita_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(null=True)),
                ('hora', models.DateTimeField(null=True)),
                ('estado', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tatuador',
            fields=[
                ('tatuador_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('especialidad', models.CharField(max_length=30, null=True)),
                ('disponibilidad', models.CharField(max_length=20, null=True)),
                ('telefono', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=40, null=True)),
                ('contrasena', models.CharField(max_length=20, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=80, null=True)),
                ('cita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cita')),
                ('tatuador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tatuador')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='tatuador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tatuador'),
        ),
    ]
